# Generated by Django 5.2.7 on 2025-12-05 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('cover_image', models.ImageField(upload_to='project_cover/')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PL', 'Planned'), ('IP', 'In Progress'), ('CO', 'Completed')], default='IP', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_image', models.ImageField(blank=True, null=True, upload_to='project_updates/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.project')),
            ],
        ),
    ]
