# Generated by Django 5.2.7 on 2025-12-05 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectsUpdate',
            new_name='ProjectUpdate',
        ),
    ]
