# Generated by Django 5.2.7 on 2025-12-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_projectsupdate_projectupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectupdate',
            name='status',
            field=models.CharField(choices=[('PL', 'Planned'), ('IP', 'In Progress'), ('CO', 'Completed')], default='IP', max_length=2),
        ),
    ]
