# Generated by Django 6.0 on 2025-12-19 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_cover_image_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(250)]),
        ),
    ]
