# Generated by Django 6.0 on 2025-12-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(default='Building2', max_length=100),
        ),
    ]
